
file:
  upload-dir: C:\uploads\profile-image
  download-url: http://localhost:8080/uploads/

# server port config
server:
  port: 8080  # server port

# db config
spring:
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver         # db driver
    url: jdbc:mariadb://db.seopia.online:3306/flex_showcase # db url
    username: seopia                           # db username
    password: qwqw13245                   # db password
  devtools:
    restart:
      enabled: false # auto restart option enabled

  # jpa config
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

# Logging Level
logging:
  level:
    root: info




